### ISSUE TITLE
Fact collection fails

### ISSUE THREAD

**Issue by ypid** [debops/ansible-debops_fact#7]
```
/etc/ansible/facts.d/debops_fact.fact
Traceback (most recent call last):
  File "/etc/ansible/facts.d/debops_fact.fact", line 62, in <module>
    output = read_facts(conf_file, output)
  File "/etc/ansible/facts.d/debops_fact.fact", line 37, in read_facts
    config.readfp(FakeDefaultSectionHead(open(conf_file)))
  File "/usr/local/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 769, in readfp
    self.read_file(fp, source=filename)
  File "/usr/local/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 724, in read_file
    self._read(f, source)
  File "/usr/local/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 1035, in _read
    for lineno, line in enumerate(fp, start=1):
TypeError: 'FakeDefaultSectionHead' object is not iterable
```

Seems that it does not matter what is contained in the `debops_fact.ini` file. If I delete it, the exception disappears as well.

**Comment by drybjed** [comment]
Do you have the INI file that was the reason for this error?

**Comment by ypid** [comment]
Seems the ini file content does not really matter. I changed the `conf_files` so that only `/etc/ansible/debops_fact.ini` is read. Content of `/etc/ansible/debops_fact.ini` does not matter. I can make it empty or use the default:

```INI
# This file is managed by Ansible, all changes will be lost.

[default]                                                                                                                                                                       
enabled = true
public_facts = "/etc/ansible/debops_fact.ini"
public_section = "global"
default_section = "default"

[global]
```

**Comment by ypid** [comment]
When I remove the `FakeDefaultSectionHead` class, it works.

**Comment by ypid** [comment]
Seems it was based on: https://stackoverflow.com/questions/2819696/parsing-properties-file-in-python/25493615#25493615

**Comment by drybjed** [comment]
@ypid Could be, I don't remember at the moment.
